version: '3.8'

services:
  bot:
    container_name: bot
    build: ./bot
    command: sh -c "sleep 5s && python3 -m event_scheduler"
    env_file:
      - ./.env
    environment:
      MONGO_URL: mongodb://db:27017
    depends_on:
      - db
    networks:
      - botnet

  db:
    container_name: db
    build: ./db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - botnet

volumes:
  dbdata:


networks:
  botnet:
    driver: bridge
